/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MapRouteImport } from './routes/map'
import { Route as HouseholdsIndexRouteImport } from './routes/households.index'
import { Route as HouseholdsIdRouteImport } from './routes/households.$id'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIndexRoute = HouseholdsIndexRouteImport.update({
  id: '/households/',
  path: '/households/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIdRoute = HouseholdsIdRouteImport.update({
  id: '/households/$id',
  path: '/households/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/households/': typeof HouseholdsIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/households': typeof HouseholdsIndexRoute
  '/incidents': typeof IncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/households/': typeof HouseholdsIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/devices'
    | '/history'
    | '/map'
    | '/households/$id'
    | '/incidents/$id'
    | '/households/'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/devices'
    | '/history'
    | '/map'
    | '/households/$id'
    | '/incidents/$id'
    | '/households'
    | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/devices'
    | '/history'
    | '/map'
    | '/households/$id'
    | '/incidents/$id'
    | '/households/'
    | '/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DevicesRoute: typeof DevicesRoute
  HistoryRoute: typeof HistoryRoute
  MapRoute: typeof MapRoute
  HouseholdsIdRoute: typeof HouseholdsIdRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
  HouseholdsIndexRoute: typeof HouseholdsIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/': {
      id: '/households/'
      path: '/households'
      fullPath: '/households/'
      preLoaderRoute: typeof HouseholdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/$id': {
      id: '/households/$id'
      path: '/households/$id'
      fullPath: '/households/$id'
      preLoaderRoute: typeof HouseholdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DevicesRoute: DevicesRoute,
  HistoryRoute: HistoryRoute,
  MapRoute: MapRoute,
  HouseholdsIdRoute: HouseholdsIdRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  HouseholdsIndexRoute: HouseholdsIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
